### ISSUE TITLE
config.xml location 

### ISSUE THREAD

**Issue by dhwanilraval** [WASdev/ci.docker#147]
I am running websphere with s2i on Openshift. But getting config.xml not found, 

config file location is
\resources\ExpressConfig\wcm\files\config

Is there any property I need to specify in server.xml?

[3/5/18 15:52:43:710 UTC] 00000077 GlobalMessage I com.dev.wcm.common.log.LogUtilJCL log executing GlobalMessageResources constructor; factory=[com.dev.wcm.web.common.global.GlobalMessageResourcesFactory@f8b62653]; config=[general]; returnNull=[{2}]
[3/5/18 15:52:43:719 UTC] 00000077 PropertyMessa I org.apache.struts.util.PropertyMessageResources <init> Initializing, config='/WEB-INF/properties/ApplicationResources', returnNull=true
[3/5/18 15:52:43:720 UTC] 00000077 GlobalMessage I com.dev.wcm.common.log.LogUtilJCL log executing GlobalMessageResources constructor; factory=[com.dev.wcm.web.common.global.GlobalMessageResourcesFactory@8774427f]; config=[ENVIRONMENT_PROP]; returnNull=[{2}]
[3/5/18 15:52:43:720 UTC] 00000077 GlobalMessage I com.dev.wcm.common.log.LogUtilJCL log executing GlobalMessageResources constructor; factory=[com.dev.wcm.web.common.global.GlobalMessageResourcesFactory@fb5250bf]; config=[devX_FX_PROP]; returnNull=[{2}]
[3/5/18 15:52:43:721 UTC] 00000077 GlobalMessage I com.dev.wcm.common.log.LogUtilJCL log executing GlobalMessageResources constructor; factory=[com.dev.wcm.web.common.global.GlobalMessageResourcesFactory@862bb982]; config=[devX_ENVIRONMENT_PROP]; returnNull=[{2}]
[3/5/18 15:52:43:732 UTC] 00000077 SystemErr     R   java.io.FileNotFoundException: Config file (config.xml) not found.
[3/5/18 15:52:43:732 UTC] 00000077 SystemErr     R   	at com.dev.wcm.common.global.Global.load(Global.java:127)
[3/5/18 15:52:43:733 UTC] 00000077 SystemErr     R   	at com.dev.wcm.web.common.struts.plugin.GlobalConfigPlugin.init(GlobalConfigPlugin.java:76)
[3/5/18 15:52:43:733 UTC] 00000077 SystemErr     R   	at org.apache.struts.action.ActionServlet.initModulePlugIns(ActionServlet.java:1158)
[3/5/18 15:52:43:733 UTC] 00000077 SystemErr     R   	at org.apache.struts.action.ActionServlet.init(ActionServlet.java:473)

**Comment by dhwanilraval** [comment]
Resolved by pointing to absolute path in jvm.properties
